M48
; DRILL file {KiCad 9.0.0} date 2025-03-23T18:58:32+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-23T18:58:32+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0790
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1180
%
G90
G05
T1
X1.2792Y-2.6575
X1.2792Y-3.1075
T2
X1.5292Y-3.0237
M30
